---
- name: Kibana
  hosts: kibana
  become: yes
  tasks:

    - name: Copy Kibana
      ansible.builtin.copy:
        src: ~/Downloads/kibana-7.10.2-amd64.deb
        dest: /tmp/kibana-7.10.2-amd64.deb
        mode: '0644'

    - name: Inst. Kibana
      ansible.builtin.apt:
        deb: /tmp/kibana-7.10.2-amd64.deb
        state: present
        update_cache: yes

    - name: Conf. hosts kibana.yml
      ansible.builtin.lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^elasticsearch.hosts:'
        line: 'elasticsearch.hosts: ["http://elastic-vm.ru-central1.internal:9200"]'
        insertafter: '^#.*elasticsearch.hosts:'
        backup: yes

    - name: port 5601
      ansible.builtin.command: ufw allow 5601
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Enable Kibana
      ansible.builtin.systemd:
        name: kibana
        enabled: true

    - name: Start Kibana
      ansible.builtin.systemd:
        name: kibana
        state: started
