- name: Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Update
      apt:
        update_cache: yes

    - name: apt Nginx
      apt:
        name: nginx
        state: present

    - name: start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
