---
- name: Inst Zabbix Serv.
  hosts: zabbix
  become: yes

  tasks:
    - name: Add Zabbix repo.
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb
        state: present

    - name: Inst. Zabbix pack.
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
        state: present
        update_cache: yes

    - name: Inst. PostgreSQL
      apt:
        name:
          - postgresql
        state: present
        update_cache: yes

    - name: PostgreSQL user
      become_user: postgres
      shell: |
        psql -c "CREATE USER zabbix WITH PASSWORD 'password';"

    - name: PostgreSQL database
      become_user: postgres
      shell: |
        createdb -O zabbix zabbix

    - name: Imp Zabbix.
      become_user: zabbix
      shell: |
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | psql zabbix

    - name: Config Zabbix serv.
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^#DBPassword='
        line: 'DBPassword=password'
        state: present

    - name: Enable and Start
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - zabbix-server
        - apache2

    - name: Restart
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - zabbix-server
        - apache2
